// Generated by CoffeeScript 1.12.7
(function() {
  (function(DOC) {
    var DELIMITER, DELIMITER_TRANSLATION, STORAGE_KEY, WAITING_COUNT, WORD_MAX_LENGTH_LIMIT, add_phrase_to_storage, add_word_to_dictionary, get_translation_from_google_dic, highlight_phrase, log;
    STORAGE_KEY = 'knop_highlight_phrase';
    DELIMITER = "\u0840";
    DELIMITER_TRANSLATION = "\u0841";
    WORD_MAX_LENGTH_LIMIT = 50;
    WAITING_COUNT = 500;
    log = function(str) {
      return console.log(str);
    };
    get_translation_from_google_dic = function() {
      var translation, word;
      try {
        word = DOC.querySelector("#gdx-bubble-host").shadowRoot.querySelector("#gdx-bubble-query").innerText;
        translation = DOC.querySelector("#gdx-bubble-host").shadowRoot.querySelector("#gdx-bubble-meaning").innerText.split(',')[0];
        if (word.length > WORD_MAX_LENGTH_LIMIT || translation > WORD_MAX_LENGTH_LIMIT) {
          log("invalid word " + word + " or translation " + translation);
          return null;
        } else {
          return [word, translation];
        }
      } catch (error) {
        return null;
      }
    };
    add_word_to_dictionary = function(elem) {
      var google_dic_finding;
      google_dic_finding = {
        start: function() {
          this.timer_id = setInterval(this.wait, 10);
          return this.count_timer_step = 0;
        },
        stop: function() {
          if (this.timer_id) {
            return clearInterval(this.timer_id);
          }
        },
        wait: function() {
          var result;
          elem = DOC.querySelector("#gdx-bubble-host");
          if ((elem && elem.shadowRoot.querySelector("#gdx-bubble-more")) || this.count_timer_step > WAITING_COUNT) {
            google_dic_finding.stop();
            result = get_translation_from_google_dic();
            log(result);
            if (result) {
              return add_phrase_to_storage(result[0], result[1]);
            }
          } else {
            return this.count_timer_step += 1;
          }
        }
      };
      return google_dic_finding.start();
    };
    highlight_phrase = function(phrases) {
      var html, i, len, phrase;
      html = DOC.body.innerHTML;
      for (i = 0, len = phrases.length; i < len; i++) {
        phrase = phrases[i];
        if (phrase.length === 0) {
          next;
        }
        html = html.replace(RegExp("" + phrase, "g"), "<span class='knop_highlight_phrase'>" + phrase + "</span>");
      }
      return DOC.body.innerHTML = html;
    };
    highlight_phrase(["Examples"]);
    add_phrase_to_storage = function(word, translation) {
      return chrome.storage.sync.get(STORAGE_KEY, function(item) {
        var new_data, obj;
        if (!chrome.runtime.error) {
          new_data = item.data || {};
          new_data[word] = translation;
          return chrome.storage.sync.set((
            obj = {},
            obj["" + STORAGE_KEY] = new_data,
            obj
          ));
        }
      });
    };
    return DOC.addEventListener("dblclick", add_word_to_dictionary);
  })(document);

}).call(this);
